# Generated by Django 5.1a1 on 2024-06-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SypmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.DateField()),
                ('namapemohon', models.CharField(max_length=255)),
                ('nokp', models.CharField(max_length=255)),
                ('notel', models.CharField(max_length=255)),
                ('notel2', models.CharField(max_length=255)),
                ('jenisbantuan', models.CharField(max_length=255)),
                ('tahunmula', models.CharField(max_length=255)),
                ('tahunberakhir', models.CharField(max_length=255)),
                ('amaunbantuan', models.IntegerField()),
                ('alamatsemasa', models.TextField(max_length=255)),
                ('alamat2', models.TextField(max_length=255)),
                ('namabapa', models.CharField(max_length=255)),
                ('nokpbapa', models.CharField(max_length=255)),
                ('notelbapa', models.CharField(max_length=255)),
                ('pekerjaan', models.CharField(max_length=255)),
                ('namaibu', models.CharField(max_length=255)),
                ('nokpibu', models.CharField(max_length=255)),
                ('notelibu', models.CharField(max_length=255)),
                ('kaum', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sypm_data',
            },
        ),
    ]
