# Generated by Django 5.1a1 on 2024-06-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysypm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sypmdata',
            name='jenisbantuan',
        ),
        migrations.RemoveField(
            model_name='sypmdata',
            name='kaum',
        ),
        migrations.RemoveField(
            model_name='sypmdata',
            name='nokpbapa',
        ),
        migrations.RemoveField(
            model_name='sypmdata',
            name='nokpibu',
        ),
        migrations.RemoveField(
            model_name='sypmdata',
            name='notel2',
        ),
        migrations.RemoveField(
            model_name='sypmdata',
            name='pekerjaan',
        ),
        migrations.RemoveField(
            model_name='sypmdata',
            name='tarikh',
        ),
        migrations.RemoveField(
            model_name='sypmdata',
            name='user',
        ),
    ]
